### ISSUE TITLE
Qwen3 MoE CUDA_ERROR_INVALID_VALUE

### ISSUE THREAD

**Issue by sempervictus** [EricLBuehler/candle-vllm#237]
Looks like an OOM from the graphs (memory usage at 93% up from mid 60s) but the error is:
```rust
2025-08-04T21:19:20.105937Z  WARN candle_vllm::openai::pipelines::llm_engine: Sending 1 tasks to 3 subprocesses

thread 'tokio-runtime-worker' panicked at src/openai/pipelines/llm_engine.rs:87:73:
called `Result::unwrap()` on an `Err` value: DriverError(CUDA_ERROR_INVALID_VALUE, "invalid argument")
   0: candle_core::error::Error::bt
   1: <core::result::Result<O,E> as candle_core::cuda_backend::error::WrapErr<O>>::w
   2: candle_core::cuda_backend::utils::Map1Any::map
   3: <candle_core::sort::ArgSort as candle_core::custom_op::CustomOp1>::cuda_fwd
   4: candle_core::storage::Storage::apply_op1
   5: candle_core::sort::<impl candle_core::tensor::Tensor>::arg_sort_last_dim
   6: candle_vllm::openai::models::qwen3_moe::DecoderLayer::forward
   7: candle_vllm::openai::models::qwen3_moe::Qwen3MoE::forward
   8: candle_vllm::openai::pipelines::pipeline::DefaultPipeline::forward
   9: candle_vllm::openai::pipelines::llm_engine::LLMEngine::generate_once
  10: rayon::iter::plumbing::Folder::consume_iter
  11: rayon::iter::plumbing::bridge_producer_consumer::helper
  12: rayon::iter::collect::collect_with_consumer
  13: rayon::iter::ParallelIterator::collect
  14: tokio::runtime::park::CachedParkThread::block_on
  15: tokio::runtime::context::runtime::enter_runtime
  16: tokio::runtime::task::raw::poll
  17: std::sys::backtrace::__rust_begin_short_backtrace
  18: core::ops::function::FnOnce::call_once{{vtable.shim}}
  19: std::sys::pal::unix::thread::Thread::new::thread_start
  20: <unknown>
  21: clone

stack backtrace:
   0:     0x556c5dfca092 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h298e0188c4a60dd7
   1:     0x556c5dff81d3 - core::fmt::write::hc5b587f52236946e
   2:     0x556c5dfc4eb3 - std::io::Write::write_fmt::hebce62fcfc51610a
   3:     0x556c5dfc9ee2 - std::sys::backtrace::BacktraceLock::print::h68c85e085563f08e
   4:     0x556c5dfcb9f3 - std::panicking::default_hook::{{closure}}::hcdd2774c873c1aab
   5:     0x556c5dfcb7d5 - std::panicking::default_hook::h119e9385dceebe8a
   6:     0x556c5dfcc405 - std::panicking::rust_panic_with_hook::h90080335a004861c
   7:     0x556c5dfcc19a - std::panicking::begin_panic_handler::{{closure}}::h9414709b2a29059d
   8:     0x556c5dfca589 - std::sys::backtrace::__rust_end_short_backtrace::h8e6c212e50611945
   9:     0x556c5dfcbe2d - __rustc[54720abec170ea9f]::rust_begin_unwind
  10:     0x556c5dff50a0 - core::panicking::panic_fmt::h33f3539bd738a04f
  11:     0x556c5dff54c6 - core::result::unwrap_failed::h80ee111e740be990
  12:     0x556c5c55e5ef - rayon::iter::plumbing::Folder::consume_iter::h8dd49b7ba038cade
  13:     0x556c5c5242c0 - rayon::iter::plumbing::bridge_producer_consumer::helper::h011fb2884c73bfb8
  14:     0x556c5c638b35 - rayon::iter::collect::collect_with_consumer::he144162f4ef2b193
  15:     0x556c5c5efba3 - rayon::iter::ParallelIterator::collect::hb14d7ef9ba647793
  16:     0x556c5c544fbd - tokio::runtime::park::CachedParkThread::block_on::h08afdae4e2367195
  17:     0x556c5c638f56 - tokio::runtime::context::runtime::enter_runtime::hdfc0909dc25874cf
  18:     0x556c5c5f0075 - tokio::runtime::task::raw::poll::hd92112664108d2cc
  19:     0x556c5df88c69 - std::sys::backtrace::__rust_begin_short_backtrace::h9151144f9583754d
  20:     0x556c5df8c1a2 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h370d4225ff68810a
  21:     0x556c5dfcf59f - std::sys::pal::unix::thread::Thread::new::thread_start::hbb2799ae4296ae38
  22:     0x7efdc5d84ac3 - <unknown>
  23:     0x7efdc5e15a04 - clone
  24:                0x0 - <unknown>

```

CC7, FP16 native

**Comment by sempervictus** [comment]
Testing now, thank you

**Comment by sempervictus** [comment]
> > Testing now, thank you
> 
> You maybe interested in this [#251](https://github.com/EricLBuehler/candle-vllm/pull/251)

Sorry, didn't see this prior - pulling and rebuilding

**Comment by guoqingbao** [comment]
> [@guoqingbao](https://github.com/guoqingbao) - when running _unquantized_, is there any way to offload layers, inputs, or maybe all of the KV cache to host-memory in order to avoid
> 
It is possible, we have offloading for deepseek which is able to be used for qwen moe models, but it comes with significant performance degradation due to frequent memory swap between host cpu and gpu. The isq for q4k is now optimized, so that you are able to load any unquantized models into gguf q4k at fatest speed. I'm working on fused gguf moe kernels for qwen3 models, the initial result (decoding speed) is very promising, hopefully, we can provide a decent solution this week.

**Comment by guoqingbao** [comment]
> Thank you [@guoqingbao](https://github.com/guoqingbao)! Rebuilding momentarily. Unfortunately our Blackwell system is still awaiting NV cards at the vendor (server is built), we have access to other kit through clients and partners but mostly we're testing _this stuff_ on our own kit to avoid liability/risk of damaging customer gear - so we're limited to a few 4-way V100 systems at the moment. Qwen3 coder running last night over a TF provider did not crash though, so at least with regular summarizations of the conversation it can "work" (unfortunately fidelity/purpose get lost pretty quickly that way and the relative "value of said work" is not worth the debugging effort after a few hours of it stabbing the code with a spork).

Is there a problem of inference accuracy degradation under ultra-long context? I have reverted #248 the custom sort kernel for qwen3 moe safetensor model (I though it was that caused your yesterday's new issue, now it seems it wasn't), and added qwen3 moe gguf model support. Q4K might not be as accurate as safetensor (fp16/bf16), but works well for most contexts. We've planning add supports for quantized kvcache, hopefully, that will make things easier.

**Comment by sempervictus** [comment]
@guoqingbao its not an inference accuracy problem, it's an overly aggressive summarization of context during long-running "conversations" between agent and model. 

Probably no need to back out #248 - i've still got it in my current build branch

<details>

```git
commit 01b460169c23a751f6e5468baeb4483301abe45d (HEAD -> 20250807, origin/master, origin/HEAD)
Author: Guoqing Bao <topon@outlook.com>
Date:   Fri Aug 8 18:32:21 2025 +0800

    Support Qwen3 MoE GGUF & fast MoE inference (#252)
    
    * Support Qwen3 MoE GGUF & fast MoE inference

commit 8b51e940edcefedf3f53fd9a4c64e500011716e4
Author: Guoqing Bao <topon@outlook.com>
Date:   Thu Aug 7 13:01:39 2025 +0800

    Use customized faster GPU quant kernel for ISQ (Q4_K). (#251)
```
</details>
and seems to be working fine.
Now seeing OOMs as OOMs not ISQl problems too:
<details>

```rust
mistralrs-svc0  | 2025-08-08T15:41:42.069161Z  WARN candle_vllm::openai::pipelines::llm_engine: Sending 1 tasks to 1 subprocesses
mistralrs-svc0  | 
mistralrs-svc0  | thread 'tokio-runtime-worker' panicked at src/openai/pipelines/llm_engine.rs:87:73:
mistralrs-svc0  | called `Result::unwrap()` on an `Err` value: DriverError(CUDA_ERROR_OUT_OF_MEMORY, "out of memory")
mistralrs-svc0  |    0: candle_core::error::Error::bt
mistralrs-svc0  |    1: <core::result::Result<O,E> as candle_core::cuda_backend::error::WrapErr<O>>::w
mistralrs-svc0  |    2: <candle_nn::ops::SoftmaxLastDim as candle_core::custom_op::CustomOp1>::cuda_fwd
mistralrs-svc0  |    3: candle_core::storage::Storage::apply_op1
mistralrs-svc0  |    4: candle_core::custom_op::<impl candle_core::tensor::Tensor>::apply_op1_no_bwd
mistralrs-svc0  |    5: candle_nn::ops::softmax_last_dim
mistralrs-svc0  |    6: candle_vllm::paged_attention::PagedAttention::forward
mistralrs-svc0  |    7: candle_vllm::openai::models::qwen3_moe::DecoderLayer::forward
mistralrs-svc0  |    8: candle_vllm::openai::models::qwen3_moe::Qwen3MoE::forward
mistralrs-svc0  |    9: candle_vllm::openai::pipelines::pipeline::DefaultPipeline::forward
mistralrs-svc0  |   10: candle_vllm::openai::pipelines::llm_engine::LLMEngine::generate_once
mistralrs-svc0  |   11: rayon::iter::plumbing::Folder::consume_iter
mistralrs-svc0  |   12: rayon::iter::plumbing::bridge_producer_consumer::helper
mistralrs-svc0  |   13: rayon::iter::collect::collect_with_consumer
mistralrs-svc0  |   14: tokio::runtime::handle::Handle::block_on
mistralrs-svc0  |   15: candle_vllm::openai::pipelines::llm_engine::LLMEngine::new::{{closure}}
mistralrs-svc0  |   16: tokio::runtime::task::raw::poll
mistralrs-svc0  |   17: std::sys::backtrace::__rust_begin_short_backtrace
mistralrs-svc0  |   18: core::ops::function::FnOnce::call_once{{vtable.shim}}
mistralrs-svc0  |   19: std::sys::pal::unix::thread::Thread::new::thread_start
mistralrs-svc0  |   20: <unknown>
mistralrs-svc0  |   21: clone
mistralrs-svc0  | 
mistralrs-svc0  | stack backtrace:
mistralrs-svc0  |    0:     0x555708fc9652 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::haf222f81993ff8c8
mistralrs-svc0  |    1:     0x555708ff7e8f - core::fmt::write::h427726eeb6a9cb89
mistralrs-svc0  |    2:     0x555708fc4203 - std::io::Write::write_fmt::h417c35f5081dc132
mistralrs-svc0  |    3:     0x555708fc94a2 - std::sys::backtrace::BacktraceLock::print::h64111c32b4dcf813
mistralrs-svc0  |    4:     0x555708fcaf74 - std::panicking::default_hook::{{closure}}::hfdafe78901c32c88
mistralrs-svc0  |    5:     0x555708fcad95 - std::panicking::default_hook::h33367eaab21314b1
mistralrs-svc0  |    6:     0x555708fcb985 - std::panicking::panic_with_hook::h6e5ef4df3e9bbd20
mistralrs-svc0  |    7:     0x555708fcb71a - std::panicking::begin_panic_handler::{{closure}}::heae18cfe0b84288c
mistralrs-svc0  |    8:     0x555708fc9b59 - std::sys::backtrace::__rust_end_short_backtrace::hf367e296588d09c4
mistralrs-svc0  |    9:     0x555708fcb3ad - __rustc[a5fd53d223c672bb]::rust_begin_unwind
mistralrs-svc0  |   10:     0x555708ff4d60 - core::panicking::panic_fmt::h85898ebe8a9eaf71
mistralrs-svc0  |   11:     0x555708ff5186 - core::result::unwrap_failed::h1519ccd14bd04319
mistralrs-svc0  |   12:     0x5557076503ef - rayon::iter::plumbing::Folder::consume_iter::hdac232811593b115
mistralrs-svc0  |   13:     0x5557074fa0b1 - rayon::iter::plumbing::bridge_producer_consumer::helper::ha6b51553b5c457f5
mistralrs-svc0  |   14:     0x5557075d4595 - rayon::iter::collect::collect_with_consumer::hca1b74ed305fcfbf
mistralrs-svc0  |   15:     0x5557074e5b4a - tokio::runtime::handle::Handle::block_on::h6560c9ce959858fc
mistralrs-svc0  |   16:     0x555707558bfb - candle_vllm::openai::pipelines::llm_engine::LLMEngine::new::{{closure}}::h951f68be45723c22
mistralrs-svc0  |   17:     0x5557075d4db0 - tokio::runtime::task::raw::poll::h7076bd5d6e873a70
mistralrs-svc0  |   18:     0x555708f84ea8 - std::sys::backtrace::__rust_begin_short_backtrace::hd5f8792d17f52a8b
mistralrs-svc0  |   19:     0x555708f91b32 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h8a73802bd5f0a40c
mistralrs-svc0  |   20:     0x555708fceb5f - std::sys::pal::unix::thread::Thread::new::thread_start::hdd856e91d402ae5a
mistralrs-svc0  |   21:     0x7f93e6c64ac3 - <unknown>
mistralrs-svc0  |   22:     0x7f93e6cf5a04 - clone
mistralrs-svc0  |   23:                0x0 - <unknown>
```
</details>

**Comment by guoqingbao** [comment]
> [@guoqingbao](https://github.com/guoqingbao) its not an inference accuracy problem, it's an overly aggressive summarization of context during long-running "conversations" between agent and model.
> 
> Probably no need to back out [#248](https://github.com/EricLBuehler/candle-vllm/pull/248) - i've still got it in my current build branch
> 
> and seems to be working fine. Now seeing OOMs as OOMs not ISQl problems too:

OK, let's keep it's current format and improve kvcache for even larger context.

**Comment by sempervictus** [comment]
So this **does** intermittently still crash w/
```rust
mistralrs-svc0  | 2025-08-08T23:20:15.621061Z  INFO candle_vllm::openai::openai_server: SamplingParams { n: 1, best_of: 1, presence_penalty: 0.0, frequency_penalty: 0.0, repetition_penalty: None, repeat_last_n: None, temperature: Some(0.7), top_p: Some(0.8), top_k: Some(20), use_beam_search: false, length_penalty: 1.0, early_stopping: UnlikelyBetterCandidates, stop: None, stop_token_ids: [], ignore_eos: false, max_tokens: 20480, logprobs: None, prompt_logprobs: None, skip_special_tokens: true, thinking: None }
mistralrs-svc0  | 2025-08-08T23:20:15.621227Z  WARN candle_vllm::openai::pipelines::llm_engine: New Request with length 66024 (cmpl-c5096cb4-c582-43bf-a1f1-646bf1410c77).
mistralrs-svc0  | 2025-08-08T23:20:16.124237Z  WARN candle_vllm::openai::pipelines::llm_engine: Sending 1 tasks to 3 subprocesses
mistralrs-svc0  | 
mistralrs-svc0  | thread 'tokio-runtime-worker' panicked at src/openai/pipelines/llm_engine.rs:87:73:
mistralrs-svc0  | called `Result::unwrap()` on an `Err` value: DriverError(CUDA_ERROR_INVALID_VALUE, "invalid argument")
mistralrs-svc0  |    0: candle_core::error::Error::bt
mistralrs-svc0  |    1: <core::result::Result<O,E> as candle_core::cuda_backend::error::WrapErr<O>>::w
mistralrs-svc0  |    2: candle_core::quantized::cuda::quantize_q8_1
mistralrs-svc0  |    3: candle_core::quantized::cuda::QCudaStorage::fwd
mistralrs-svc0  |    4: <candle_core::quantized::QTensor as candle_core::custom_op::CustomOp1>::cuda_fwd
mistralrs-svc0  |    5: candle_core::storage::Storage::apply_op1
mistralrs-svc0  |    6: candle_core::custom_op::<impl candle_core::tensor::Tensor>::apply_op1_no_bwd
mistralrs-svc0  |    7: <candle_core::quantized::QMatMul as candle_core::Module>::forward
mistralrs-svc0  |    8: candle_vllm::openai::models::linear::QLinear::forward_no_dequant
mistralrs-svc0  |    9: <candle_vllm::openai::models::linear::QLinear as candle_core::Module>::forward
mistralrs-svc0  |   10: candle_vllm::openai::distributed::TensorParallelColumnLinear::forward
mistralrs-svc0  |   11: candle_vllm::openai::models::qwen3_moe::DecoderLayer::forward
mistralrs-svc0  |   12: candle_vllm::openai::models::qwen3_moe::Qwen3MoE::forward
...
```
in **some** cases when approaching memory limit and in others it spits out the OOM error. Looks like we're getting _closer_. Is there some way to reset state on-error without having to manually restart the PID/container? Maybe something like a flag to exit on crash could be useful to auto-restart

**Comment by sempervictus** [comment]
personally figure that "accuracy of calculation supersedes performance consideration" (esp for MM) so all for using an appropriate sort for it. Maybe that could be a tunable parameter of some sort similar to how R1 has ranked offload? Also just hit this same `q8_1` bug on the single-GPU GGUF as well:
```rust
mistralrs-svc0  | thread 'tokio-runtime-worker' panicked at src/openai/pipelines/llm_engine.rs:87:73:
mistralrs-svc0  | called `Result::unwrap()` on an `Err` value: DriverError(CUDA_ERROR_INVALID_VALUE, "invalid argument")
mistralrs-svc0  |    0: candle_core::error::Error::bt
mistralrs-svc0  |    1: <core::result::Result<O,E> as candle_core::cuda_backend::error::WrapErr<O>>::w
mistralrs-svc0  |    2: candle_core::quantized::cuda::quantize_q8_1
mistralrs-svc0  |    3: candle_core::quantized::cuda::QCudaStorage::indexed_moe_forward
mistralrs-svc0  |    4: candle_core::quantized::QTensor::indexed_moe_forward
mistralrs-svc0  |    5: candle_core::quantized::QMatMul::indexed_moe_forward
mistralrs-svc0  |    6: candle_vllm::openai::models::quantized_qwen3_moe::MoeOrMlp::forward
mistralrs-svc0  |    7: candle_vllm::openai::models::quantized_qwen3_moe::GGUFQWenMoE::forward
mistralrs-svc0  |    8: candle_vllm::openai::pipelines::pipeline::DefaultPipeline::forward
mistralrs-svc0  |    9: candle_vllm::openai::pipelines::llm_engine::LLMEngine::generate_once
mistralrs-svc0  |   10: rayon::iter::plumbing::Folder::consume_iter
mistralrs-svc0  |   11: rayon::iter::plumbing::bridge_producer_consumer::helper
mistralrs-svc0  |   12: rayon::iter::collect::collect_with_consumer
mistralrs-svc0  |   13: tokio::runtime::handle::Handle::block_on
mistralrs-svc0  |   14: candle_vllm::openai::pipelines::llm_engine::LLMEngine::new::{{closure}}
mistralrs-svc0  |   15: tokio::runtime::task::raw::poll
mistralrs-svc0  |   16: std::sys::backtrace::__rust_begin_short_backtrace
mistralrs-svc0  |   17: core::ops::function::FnOnce::call_once{{vtable.shim}}
mistralrs-svc0  |   18: std::sys::pal::unix::thread::Thread::new::thread_start
mistralrs-svc0  |   19: <unknown>
mistralrs-svc0  |   20: clone
```
... if that can be spread out to multiple GPUs and have KV cache offload with the accurate sorting algorithm in-play and even half of the per-GPU performance we see w/ the `unsloth` GGUF then i think we might be able to actually give it fairly complex tasks to sort through

**Comment by guoqingbao** [comment]
> personally figure that "accuracy of calculation supersedes performance consideration" (esp for MM) so all for using an appropriate sort for it. Maybe that could be a tunable parameter of some sort similar to how R1 has ranked offload? Also just hit this same `q8_1` bug on the single-GPU GGUF as well:
> 
> mistralrs-svc0  | thread 'tokio-runtime-worker' panicked at src/openai/pipelines/llm_engine.rs:87:73:
> mistralrs-svc0  | called `Result::unwrap()` on an `Err` value: DriverError(CUDA_ERROR_INVALID_VALUE, "invalid argument")
> mistralrs-svc0  |    0: candle_core::error::Error::bt
> mistralrs-svc0  |    1: <core::result::Result<O,E> as candle_core::cuda_backend::error::WrapErr<O>>::w
> mistralrs-svc0  |    2: candle_core::quantized::cuda::quantize_q8_1
> mistralrs-svc0  |    3: candle_core::quantized::cuda::QCudaStorage::indexed_moe_forward
> mistralrs-svc0  |    4: candle_core::quantized::QTensor::indexed_moe_forward
> mistralrs-svc0  |    5: candle_core::quantized::QMatMul::indexed_moe_forward
> mistralrs-svc0  |    6: candle_vllm::openai::models::quantized_qwen3_moe::MoeOrMlp::forward
> mistralrs-svc0  |    7: candle_vllm::openai::models::quantized_qwen3_moe::GGUFQWenMoE::forward
> mistralrs-svc0  |    8: candle_vllm::openai::pipelines::pipeline::DefaultPipeline::forward
> mistralrs-svc0  |    9: candle_vllm::openai::pipelines::llm_engine::LLMEngine::generate_once
> mistralrs-svc0  |   10: rayon::iter::plumbing::Folder::consume_iter
> mistralrs-svc0  |   11: rayon::iter::plumbing::bridge_producer_consumer::helper
> mistralrs-svc0  |   12: rayon::iter::collect::collect_with_consumer
> mistralrs-svc0  |   13: tokio::runtime::handle::Handle::block_on
> mistralrs-svc0  |   14: candle_vllm::openai::pipelines::llm_engine::LLMEngine::new::{{closure}}
> mistralrs-svc0  |   15: tokio::runtime::task::raw::poll
> mistralrs-svc0  |   16: std::sys::backtrace::__rust_begin_short_backtrace
> mistralrs-svc0  |   17: core::ops::function::FnOnce::call_once{{vtable.shim}}
> mistralrs-svc0  |   18: std::sys::pal::unix::thread::Thread::new::thread_start
> mistralrs-svc0  |   19: <unknown>
> mistralrs-svc0  |   20: clone
> ... if that can be spread out to multiple GPUs and have KV cache offload with the accurate sorting algorithm in-play and even half of the per-GPU performance we see w/ the `unsloth` GGUF then i think we might be able to actually give it fairly complex tasks to sort through

I just tested ultra long text, the loading of qwen3 moe 32B safetensor model on multiple rank with or without isq q4k should work, but the loading of gguf model for long context still have the CUDA_ERROR_INVALID_VALUE.

I will try to fix the GGUF model.

**Comment by sempervictus** [comment]
@guoqingbao: With ISQ 4 at least on CC7, you can still run into the `candle_core::quantized::cuda::quantize_q8_1` error but it doesn't happen every time - after your recent fixes it sometimes throws the correct out of memory error. Even with 128G of VRAM however, it usually runs out of VRAM before running out of context window space (and if we can get the 1m ctx window capability, then "definitely" vs "usually")

When you say ultra long text - how much memory and how much were you able to cram into it? 😄 Guessing at least 160G if you have more than one of those A100s on-hand?

**Comment by guoqingbao** [comment]
> [@guoqingbao](https://github.com/guoqingbao): With ISQ 4 at least on CC7, you can still run into the `candle_core::quantized::cuda::quantize_q8_1` error but it doesn't happen every time - after your recent fixes it sometimes throws the correct out of memory error. Even with 128G of VRAM however, it usually runs out of VRAM before running out of context window space (and if we can get the 1m ctx window capability, then "definitely" vs "usually")
> 
> When you say ultra long text - how much memory and how much were you able to cram into it? 😄 Guessing at least 160G if you have more than one of those A100s on-hand?

The Qwen3 GGUF MoE quantize_q8_1 error is fixed in #255 

I have 8 A100s available to use but I didn't test that long in one card, usually 128k context.

**Comment by sempervictus** [comment]
I guess the rough analog would be 2xA100 for ~30GB more VRAM but still rank-splitting; you have BF16 though which makes "a bit" of a difference.

Thanks for pushing that fix, pulling/building/testing.

**Comment by guoqingbao** [comment]
> quantize_q8_1

That's the bug for `candle quantize_q8_1`, I have revised the MoE one but others using gguf format still call unprotected quantize_q8_1 (it happens when the number of input tokens exceed some limits, i.e., 65535, the maximum dim for the second gridDim in kernel launch). I will make a permanent solution to protect all callers of quantize_q8_1, not just the MoE one.

**Comment by guoqingbao** [comment]
> [@guoqingbao](https://github.com/guoqingbao) - so at least with `--isq q4k` i am still fairly reliably able to reproduce:
> 
> mistralrs-svc0  | 2025-08-09T13:04:24.259554Z  WARN candle_vllm::openai::pipelines::llm_engine: New Request with length 66781 (cmpl-0c4c280e-8912-4bb1-8f64-d809cedef482).
> mistralrs-svc0  | 2025-08-09T13:04:24.762841Z  WARN candle_vllm::openai::pipelines::llm_engine: Sending 1 tasks to 3 subprocesses
> mistralrs-svc0  | 
> mistralrs-svc0  | thread 'tokio-runtime-worker' panicked at src/openai/pipelines/llm_engine.rs:87:73:
> mistralrs-svc0  | called `Result::unwrap()` on an `Err` value: DriverError(CUDA_ERROR_INVALID_VALUE, "invalid argument")
> mistralrs-svc0  |    0: candle_core::error::Error::bt
> mistralrs-svc0  |    1: <core::result::Result<O,E> as candle_core::cuda_backend::error::WrapErr<O>>::w
> mistralrs-svc0  |    2: candle_core::quantized::cuda::quantize_q8_1
> mistralrs-svc0  |    3: candle_core::quantized::cuda::QCudaStorage::fwd
> mistralrs-svc0  |    4: <candle_core::quantized::QTensor as candle_core::custom_op::CustomOp1>::cuda_fwd
> mistralrs-svc0  |    5: candle_core::storage::Storage::apply_op1
> mistralrs-svc0  |    6: candle_core::custom_op::<impl candle_core::tensor::Tensor>::apply_op1_no_bwd
> mistralrs-svc0  |    7: <candle_core::quantized::QMatMul as candle_core::Module>::forward
> mistralrs-svc0  |    8: candle_vllm::openai::models::linear::QLinear::forward_no_dequant
> mistralrs-svc0  |    9: <candle_vllm::openai::models::linear::QLinear as candle_core::Module>::forward
> mistralrs-svc0  |   10: candle_vllm::openai::distributed::TensorParallelColumnLinear::forward
> mistralrs-svc0  |   11: candle_vllm::openai::models::qwen3_moe::DecoderLayer::forward
> mistralrs-svc0  |   12: candle_vllm::openai::models::qwen3_moe::Qwen3MoE::forward
> mistralrs-svc0  |   13: candle_vllm::openai::pipelines::pipeline::DefaultPipeline::forward
> mistralrs-svc0  |   14: candle_vllm::openai::pipelines::llm_engine::LLMEngine::generate_once
> mistralrs-svc0  |   15: rayon::iter::plumbing::Folder::consume_iter
> mistralrs-svc0  |   16: rayon::iter::plumbing::bridge_producer_consumer::helper
> mistralrs-svc0  |   17: rayon::iter::collect::collect_with_consumer
> mistralrs-svc0  |   18: tokio::runtime::handle::Handle::block_on
> mistralrs-svc0  |   19: candle_vllm::openai::pipelines::llm_engine::LLMEngine::new::{{closure}}
> mistralrs-svc0  |   20: tokio::runtime::task::raw::poll
> mistralrs-svc0  |   21: std::sys::backtrace::__rust_begin_short_backtrace
> mistralrs-svc0  |   22: core::ops::function::FnOnce::call_once{{vtable.shim}}
> mistralrs-svc0  |   23: std::sys::pal::unix::thread::Thread::new::thread_start
> mistralrs-svc0  |   24: <unknown>
> mistralrs-svc0  |   25: clone
> regression of [#248](https://github.com/EricLBuehler/candle-vllm/pull/248)?

This is a fix for all entries of quantized matmul via input quant with quantize_q8_1 #256

**Comment by sempervictus** [comment]
@guoqingbao - #256 does seem to address the contents of the stack trace but the same exact result (a hung model) occurs with:
```rust
candle-vllm-swe  | 2025-08-09T19:30:20.476865Z  WARN candle_vllm::openai::pipelines::llm_engine: New Request with length 82198 (cmpl-cd030644-437d-4319-a1a7-cce894e6dbb1).
candle-vllm-swe  | 2025-08-09T19:30:20.983788Z  WARN candle_vllm::openai::pipelines::llm_engine: Sending 1 tasks to 3 subprocesses
candle-vllm-swe  | 
candle-vllm-swe  | thread 'tokio-runtime-worker' (682) panicked at src/openai/pipelines/llm_engine.rs:87:73:
candle-vllm-swe  | called `Result::unwrap()` on an `Err` value: DriverError(CUDA_ERROR_INVALID_VALUE, "invalid argument")
candle-vllm-swe  |    0: candle_core::error::Error::bt
candle-vllm-swe  |    1: <core::result::Result<O,E> as candle_core::cuda_backend::error::WrapErr<O>>::w
candle-vllm-swe  |    2: candle_core::cuda_backend::utils::Map1Any::map
candle-vllm-swe  |    3: <candle_core::sort::ArgSort as candle_core::custom_op::CustomOp1>::cuda_fwd
candle-vllm-swe  |    4: candle_core::storage::Storage::apply_op1
candle-vllm-swe  |    5: candle_core::sort::<impl candle_core::tensor::Tensor>::arg_sort_last_dim
candle-vllm-swe  |    6: candle_vllm::openai::models::qwen3_moe::DecoderLayer::forward
candle-vllm-swe  |    7: candle_vllm::openai::models::qwen3_moe::Qwen3MoE::forward
candle-vllm-swe  |    8: candle_vllm::openai::pipelines::pipeline::DefaultPipeline::forward
candle-vllm-swe  |    9: candle_vllm::openai::pipelines::llm_engine::LLMEngine::generate_once
candle-vllm-swe  |   10: rayon::iter::plumbing::Folder::consume_iter
candle-vllm-swe  |   11: rayon::iter::plumbing::bridge_producer_consumer::helper
candle-vllm-swe  |   12: rayon::iter::collect::collect_with_consumer
candle-vllm-swe  |   13: tokio::runtime::handle::Handle::block_on
candle-vllm-swe  |   14: candle_vllm::openai::pipelines::llm_engine::LLMEngine::new::{{closure}}
candle-vllm-swe  |   15: tokio::runtime::task::raw::poll
candle-vllm-swe  |   16: std::sys::backtrace::__rust_begin_short_backtrace
candle-vllm-swe  |   17: core::ops::function::FnOnce::call_once{{vtable.shim}}
candle-vllm-swe  |   18: std::sys::pal::unix::thread::Thread::new::thread_start
candle-vllm-swe  |   19: <unknown>
candle-vllm-swe  |   20: clone
candle-vllm-swe  | 
candle-vllm-swe  | stack backtrace:
candle-vllm-swe  |    0:     0x55960211d382 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::he0c12a9b908a20ff
candle-vllm-swe  |    1:     0x55960214bc3f - core::fmt::write::hd625e53c487f567c
candle-vllm-swe  |    2:     0x559602117f33 - std::io::Write::write_fmt::h903e25bab2f49303
candle-vllm-swe  |    3:     0x55960211d1d2 - std::sys::backtrace::BacktraceLock::print::hab707767c630dafb
candle-vllm-swe  |    4:     0x55960211eca4 - std::panicking::default_hook::{{closure}}::hef8140f2819f7819
candle-vllm-swe  |    5:     0x55960211eac5 - std::panicking::default_hook::h033774dbac4eb1e5
candle-vllm-swe  |    6:     0x55960211f715 - std::panicking::panic_with_hook::heae2ed06d2446c5d
candle-vllm-swe  |    7:     0x55960211f4aa - std::panicking::panic_handler::{{closure}}::he8f50a4285b5d007
candle-vllm-swe  |    8:     0x55960211d889 - std::sys::backtrace::__rust_end_short_backtrace::heb2e8724623d343f
candle-vllm-swe  |    9:     0x55960211f13d - __rustc[91f234d998cd6254]::rust_begin_unwind
candle-vllm-swe  |   10:     0x559602148b10 - core::panicking::panic_fmt::hbf8b46eb2d03ea4d
candle-vllm-swe  |   11:     0x559602148f36 - core::result::unwrap_failed::hf52ed52e8e0d98a1
candle-vllm-swe  |   12:     0x5596007909cf - rayon::iter::plumbing::Folder::consume_iter::h15f6c778341710c6
candle-vllm-swe  |   13:     0x55960064de61 - rayon::iter::plumbing::bridge_producer_consumer::helper::h3abc8c9057c6f609
candle-vllm-swe  |   14:     0x5596007c4b75 - rayon::iter::collect::collect_with_consumer::hd2254428f75d9be7
candle-vllm-swe  |   15:     0x55960063a81a - tokio::runtime::handle::Handle::block_on::h18858e2cef86bac5
candle-vllm-swe  |   16:     0x5596006ad96b - candle_vllm::openai::pipelines::llm_engine::LLMEngine::new::{{closure}}::h95190816607d8079
candle-vllm-swe  |   17:     0x5596007c51b0 - tokio::runtime::task::raw::poll::h7f88aff485f0fcfd
candle-vllm-swe  |   18:     0x5596020d8b78 - std::sys::backtrace::__rust_begin_short_backtrace::h373c59dd319d7038
candle-vllm-swe  |   19:     0x5596020e5842 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hc4a2228620583cd2
candle-vllm-swe  |   20:     0x55960212290f - std::sys::pal::unix::thread::Thread::new::thread_start::h17f0450f415adfa3
candle-vllm-swe  |   21:     0x7f142d384ac3 - <unknown>
candle-vllm-swe  |   22:     0x7f142d415a04 - clone
candle-vllm-swe  |   23:                0x0 - <unknown>
```

**Comment by guoqingbao** [comment]
> [@guoqingbao](https://github.com/guoqingbao) - [#256](https://github.com/EricLBuehler/candle-vllm/pull/256) does seem to address the contents of the stack trace but the same exact result (a hung model) occurs with:
> 
> candle-vllm-swe  | 2025-08-09T19:30:20.476865Z  WARN candle_vllm::openai::pipelines::llm_engine: New Request with length 82198 (cmpl-cd030644-437d-4319-a1a7-cce894e6dbb1).
> candle-vllm-swe  | 2025-08-09T19:30:20.983788Z  WARN candle_vllm::openai::pipelines::llm_engine: Sending 1 tasks to 3 subprocesses
> candle-vllm-swe  | 
> candle-vllm-swe  | thread 'tokio-runtime-worker' (682) panicked at src/openai/pipelines/llm_engine.rs:87:73:
> candle-vllm-swe  | called `Result::unwrap()` on an `Err` value: DriverError(CUDA_ERROR_INVALID_VALUE, "invalid argument")
> candle-vllm-swe  |    0: candle_core::error::Error::bt
> candle-vllm-swe  |    1: <core::result::Result<O,E> as candle_core::cuda_backend::error::WrapErr<O>>::w
> candle-vllm-swe  |    2: candle_core::cuda_backend::utils::Map1Any::map
> candle-vllm-swe  |    3: <candle_core::sort::ArgSort as candle_core::custom_op::CustomOp1>::cuda_fwd
> candle-vllm-swe  |    4: candle_core::storage::Storage::apply_op1
> candle-vllm-swe  |    5: candle_core::sort::<impl candle_core::tensor::Tensor>::arg_sort_last_dim
> candle-vllm-swe  |    6: candle_vllm::openai::models::qwen3_moe::DecoderLayer::forward
> candle-vllm-swe  |    7: candle_vllm::openai::models::qwen3_moe::Qwen3MoE::forward
> candle-vllm-swe  |    8: candle_vllm::openai::pipelines::pipeline::DefaultPipeline::forward
> candle-vllm-swe  |    9: candle_vllm::openai::pipelines::llm_engine::LLMEngine::generate_once
> candle-vllm-swe  |   10: rayon::iter::plumbing::Folder::consume_iter
> candle-vllm-swe  |   11: rayon::iter::plumbing::bridge_producer_consumer::helper
> candle-vllm-swe  |   12: rayon::iter::collect::collect_with_consumer
> candle-vllm-swe  |   13: tokio::runtime::handle::Handle::block_on
> candle-vllm-swe  |   14: candle_vllm::openai::pipelines::llm_engine::LLMEngine::new::{{closure}}
> candle-vllm-swe  |   15: tokio::runtime::task::raw::poll
> candle-vllm-swe  |   16: std::sys::backtrace::__rust_begin_short_backtrace
> candle-vllm-swe  |   17: core::ops::function::FnOnce::call_once{{vtable.shim}}
> candle-vllm-swe  |   18: std::sys::pal::unix::thread::Thread::new::thread_start
> candle-vllm-swe  |   19: <unknown>
> candle-vllm-swe  |   20: clone
> candle-vllm-swe  | 
> candle-vllm-swe  | stack backtrace:
> candle-vllm-swe  |    0:     0x55960211d382 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::he0c12a9b908a20ff
> candle-vllm-swe  |    1:     0x55960214bc3f - core::fmt::write::hd625e53c487f567c
> candle-vllm-swe  |    2:     0x559602117f33 - std::io::Write::write_fmt::h903e25bab2f49303
> candle-vllm-swe  |    3:     0x55960211d1d2 - std::sys::backtrace::BacktraceLock::print::hab707767c630dafb
> candle-vllm-swe  |    4:     0x55960211eca4 - std::panicking::default_hook::{{closure}}::hef8140f2819f7819
> candle-vllm-swe  |    5:     0x55960211eac5 - std::panicking::default_hook::h033774dbac4eb1e5
> candle-vllm-swe  |    6:     0x55960211f715 - std::panicking::panic_with_hook::heae2ed06d2446c5d
> candle-vllm-swe  |    7:     0x55960211f4aa - std::panicking::panic_handler::{{closure}}::he8f50a4285b5d007
> candle-vllm-swe  |    8:     0x55960211d889 - std::sys::backtrace::__rust_end_short_backtrace::heb2e8724623d343f
> candle-vllm-swe  |    9:     0x55960211f13d - __rustc[91f234d998cd6254]::rust_begin_unwind
> candle-vllm-swe  |   10:     0x559602148b10 - core::panicking::panic_fmt::hbf8b46eb2d03ea4d
> candle-vllm-swe  |   11:     0x559602148f36 - core::result::unwrap_failed::hf52ed52e8e0d98a1
> candle-vllm-swe  |   12:     0x5596007909cf - rayon::iter::plumbing::Folder::consume_iter::h15f6c778341710c6
> candle-vllm-swe  |   13:     0x55960064de61 - rayon::iter::plumbing::bridge_producer_consumer::helper::h3abc8c9057c6f609
> candle-vllm-swe  |   14:     0x5596007c4b75 - rayon::iter::collect::collect_with_consumer::hd2254428f75d9be7
> candle-vllm-swe  |   15:     0x55960063a81a - tokio::runtime::handle::Handle::block_on::h18858e2cef86bac5
> candle-vllm-swe  |   16:     0x5596006ad96b - candle_vllm::openai::pipelines::llm_engine::LLMEngine::new::{{closure}}::h95190816607d8079
> candle-vllm-swe  |   17:     0x5596007c51b0 - tokio::runtime::task::raw::poll::h7f88aff485f0fcfd
> candle-vllm-swe  |   18:     0x5596020d8b78 - std::sys::backtrace::__rust_begin_short_backtrace::h373c59dd319d7038
> candle-vllm-swe  |   19:     0x5596020e5842 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hc4a2228620583cd2
> candle-vllm-swe  |   20:     0x55960212290f - std::sys::pal::unix::thread::Thread::new::thread_start::h17f0450f415adfa3
> candle-vllm-swe  |   21:     0x7f142d384ac3 - <unknown>
> candle-vllm-swe  |   22:     0x7f142d415a04 - clone
> candle-vllm-swe  |   23:                0x0 - <unknown>

That's candle's another bug candle_core::tensor::Tensor>::arg_sort_last_dim, I thought it shoud not crash because it's last dim is 128, not that large for kernel launch, but the crash requires us to take #248 back.

**Comment by guoqingbao** [comment]
Damm! the crash is here:

https://github.com/huggingface/candle/blob/main/candle-core/src/sort.rs

```rust
let ncols = self.last_dim;
            let nrows = elem_count / ncols;
            let ncols_pad = next_power_of_2(ncols);
            let cfg = LaunchConfig {
                grid_dim: (1, nrows as u32, 1),
                block_dim: (ncols_pad as u32, 1, 1),
                shared_mem_bytes: (ncols_pad * std::mem::size_of::<u32>()) as u32,
            };
```
They use nrows as gridDim.y (which has limits of 65535), I don't know why there are so many such low level bugs inside candle, they do not care the actual usage, idealy think the input rows will not exceed 65535, they can put nrows as first gridDim, gridDim.y has much much larger limits. 

@EricLBuehler It seems we need to report these serious issue to the candle.

**Comment by guoqingbao** [comment]
Fixed over here #257 I think this CUDA_ERROR_INVALID_VALUE kernel launch  bug can be finally closed :)

**Comment by sempervictus** [comment]
@guoqingbao - so far so good, closing for now unless i somehow trip this again :-)
